version: '3.8'
services:
  pet-reports-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=movies-now-db
      - POSTGRES_USER=moviesnow
      - POSTGRES_PASSWORD=moviesnow
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local